Device: cuda
Note: None
Project: CoRL2022
Save: test_june18
Seed: 6
Task: walking
Max Steps: 10000000
Steps Per Evaluation: 20000
Steps Per Video: 100000
Episodes Per Evaluation: 5
Steps Per Episode: 1800
